export default {
    products:[{
        _id: '1',
        name: "Women's Polka Dot Twofer Dress",
        category: "Office Dresses",
        image: '/Images/Office1.jpg',
        price: 54.99,
        brand: 'By Venus',
        rating: 4.5,
        numReviews: 10,
        countInStock: 5,
        description: 'Black & white long sleeve'
    },
    {
        _id: '2',
        name: "Women's Open Front Solid Blazer & Pants Set",
        category: "Office Dresses",
        image: '/Images/Office2.jpg',
        price: 52.00,
        brand: 'By Shein',
        rating: 4.3,
        numReviews: 12,
        countInStock: 7,
        description: 'Elegant long sleeve, regular fit'
    },
    {
        _id: '3',
        name: "The Neck Jumpsuit",
        category: "Office Dresses",
        image: '/Images/Office3.jpg',
        price: 49.00,
        brand: 'By Venus',
        rating: 4,
        numReviews: 9,
        countInStock: 10,
        description: 'Tie detail at neck, side pockets'
    },
    {
        _id: '4',
        name: "Floral Sharkbite Dress",
        category: "Summer Dresses",
        image: '/Images/Summer1.jpg',
        price: 49.00,
        brand: 'By Venus',
        rating: 4.5,
        numReviews: 15,
        countInStock: 9,
        description: 'Elastic at waist, stretched fabric'
    },
    {
        _id: '5',
        name: "Floral Wrap Round Neckline Midi X-line Dress",
        category: "Summer Dresses",
        image: '/Images/Summer2.jpg',
        price: 71.99,
        brand: 'By Venus',
        rating: 4.5,
        numReviews: 5,
        countInStock: 5,
        description: 'color=Green, plus size available'
    },
    {
        _id: '6',
        name: "Plus Sweetheart Neck Belted Sunflower A-line Dress",
        category: "Summer Dresses",
        image: '/Images/Summer3.jpg',
        price: 49.99,
        brand: 'By Shein',
        rating: 4.7,
        numReviews: 10,
        countInStock: 6,
        description: 'belt at waist, plus size'
    },
    {
        _id: '7',
        name: "Women's Sequin Detail Party Dress",
        category: "Party Dresses",
        image: '/Images/Party1.jpg',
        price: 59.00,
        brand: 'By Venus',
        rating: 4.8,
        numReviews: 8,
        countInStock: 9,
        description: 'Perfect & dance-all-night style'
    },
    {
        _id: '8',
        name: "Chiffon Overlay Cold Sholder High Low Less dress",
        category: "Party Dresses",
        image: '/Images/Party2.jpg',
        price: 49.99,
        brand: 'By Shein',
        rating: 4.5,
        numReviews: 5,
        countInStock: 11,
        description: 'V neck, Short sleeve, cold shoulder'
    },
    {
        _id: '9',
        name: "Sequin Detail Sleevless Peacock Blue Party Dress",
        category: "Party Dresses",
        image: '/Images/Party3.jpg',
        price: 66.00,
        brand: 'By Venus',
        rating: 5,
        numReviews: 1,
        countInStock: 5,
        description: 'solid, Maxi, High waist, Blue'
    },
    {
        _id: '10',
        name: "Plus Size Elegant Dress",
        category: "Plus Size Dresses",
        image: '/Images/PS1.jpg',
        price: 59.00,
        brand: 'By Venus',
        rating: 4.5,
        numReviews: 10,
        countInStock: 2,
        description: 'Black, V neck, long sleeve'
    },
    {
        _id: '11',
        name: "Plus Size Cold Shoulder Dress",
        category: "Plus Size Dresses",
        image: '/Images/PS2.jpg',
        price: 60.00,
        brand: 'By Shein',
        rating: 4.9,
        numReviews: 10,
        countInStock: 4,
        description: 'Round neck, High waist, short sleeve'
    },
    {
        _id: '12',
        name: "Plus Solid Tie Waist Dress",
        category: "Plus Size Dresses",
        image: '/Images/PS3.jpg',
        price: 44.99,
        brand: 'By Shein',
        rating: 4.7,
        numReviews: 7,
        countInStock: 3,
        description: 'Round neck, High waist, pink, elastic at waist'
    },
]
}

